### ISSUE TITLE
install.py fails due to missing bin dir

### ISSUE THREAD

**Issue by connortechnology** [baudneo/zomi-server#1]
When using examples/install.py the bin directory isn't created in dest, so install fails. Manually creating allows install to continue.

**Comment by connortechnology** [comment]
fails installing mlapi.py into /opt/zomi/server/data/bin/

**Comment by baudneo** [comment]
The bin dir *should* exist, it is created in the beginning before any files are copied over.

```
install_dirs(
        data_dir,
        DEFAULT_DATA_DIR,
        "Data",
        sub_dirs=[
            "models",
            "push",
            "scripts",
            "images",
            "bin",
            "misc",
        ],
    )
```

This should create the `data_dir` and the listed sub directories.
